language: c

os:
  - linux
  - osx

sudo: required

dist:
  - trusty
  - xenial

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true

env:
  - SCRIPT_UNDER_TEST=ci-dev
  - SCRIPT_UNDER_TEST=install-bake
  - SCRIPT_UNDER_TEST=install-corto-src
  - SCRIPT_UNDER_TEST=install-dev-src
  - SCRIPT_UNDER_TEST=install-doc-src
  - SCRIPT_UNDER_TEST=install-release-src
  - SCRIPT_UNDER_TEST=install-web-src

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - ./"${SCRIPT_UNDER_TEST}"
